### ISSUE TITLE
Why is the sync going through every user?

### ISSUE THREAD

**Issue by JustKiddingCode** [lbrocke/gitea-ldap-team-sync#1]
Wouldn't it be easier to reverse the mapping?
I.e. list every organisation/team with their ldap groups and walk through the organisation & team and add every user?
3-for loops doesn't seem so straight forward to me.

**Comment by lbrocke** [comment]
That would be possible of course, however that still requires 3 for-loops if I understand you correctly:
```
for all users:
    for all mappings (org, team, ldap_group):
        for all teams:
            if user has required LDAP group, add to team; continue
            if user is in team but not in LDAP group, remove from team
```
Looping the mappings and teams first and the users last would result in 3 loops as well.
