### ISSUE TITLE
Why do you always make things so complicated

### ISSUE THREAD

**Issue by JustKiddingCode** [lbrocke/gitea-ldap-team-sync#2]
aka
```
<bool a> 
if a == True:
return True
else:
return False
```
https://github.com/lbrocke/gitea-ldap-team-sync/blob/ce5dae83f8b75eb7859aaac6eb33ca3a65684387/gitea-ldap-team-sync.py#L104

**Comment by lbrocke** [comment]
Did overlook that, fixed it.
